### PR TITLE
Travis-CI happy

### PR DESCRIPTION
**Pull request by hakatashi**
Set up integration with Travis-CI immediately

### CODE REVIEW

**Comment by sindresorhus** [comment]
What is this PR supposed to improve? It's not clear.

**Comment by hakatashi** [comment]
When I do `yo jquery`, publish it to GitHub, and set up integration with Travis-CI, the build job just fails. ([here is my log](https://travis-ci.org/hakatashi/jquery.howmuchread/jobs/65057714)) I had to work some debugs. Suppose this patch makes it work well. Thanks.

**Comment by stevemao** [comment]
:+1:

**Comment by SBoudrias** [comment]
Thanks

**Pull request merged**
